#!/bin/bash
red='\e[1;31m'
green='\e[1;32m' 
blue='\e[1;34m' 
purple='\e[1;35m'
cyan='\e[1;36m' 
white='\e[1;37m'
yellow='\e[1;33m'

banner() {

printf "\n\n"

printf "     ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄▄  ▄               ▄  ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄              ▄▄▄▄      ▄▄▄▄▄▄▄▄▄▄▄ "
printf "    ▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌▐░▌             ▐░▌▐░░░░░░░░░░░▌▐░░░░░░░░░░▌           ▄█░░░░▌    ▐░░░░░░░░░░░▌"
printf "    ▐░█▀▀▀▀▀▀▀▀▀ ▐░█▀▀▀▀▀▀▀█░▌ ▐░▌           ▐░▌  ▀▀▀▀█░█▀▀▀▀ ▐░█▀▀▀▀▀▀▀█░▌         ▐░░▌▐░░▌    ▐░█▀▀▀▀▀▀▀█░▌"
printf "    ▐░▌          ▐░▌       ▐░▌  ▐░▌         ▐░▌       ▐░▌     ▐░▌       ▐░▌          ▀▀ ▐░░▌    ▐░▌       ▐░▌"
printf "    ▐░▌          ▐░▌       ▐░▌   ▐░▌       ▐░▌        ▐░▌     ▐░▌       ▐░▌ ▄▄▄▄▄▄▄▄▄▄▄ ▐░░▌    ▐░█▄▄▄▄▄▄▄█░▌"
printf "    ▐░▌          ▐░▌       ▐░▌    ▐░▌     ▐░▌         ▐░▌     ▐░▌       ▐░▌▐░░░░░░░░░░░▌▐░░▌    ▐░░░░░░░░░░░▌"
printf "    ▐░▌          ▐░▌       ▐░▌     ▐░▌   ▐░▌          ▐░▌     ▐░▌       ▐░▌ ▀▀▀▀▀▀▀▀▀▀▀ ▐░░▌     ▀▀▀▀▀▀▀▀▀█░▌"
printf "    ▐░▌          ▐░▌       ▐░▌      ▐░▌ ▐░▌           ▐░▌     ▐░▌       ▐░▌             ▐░░▌              ▐░▌"
printf "    ▐░█▄▄▄▄▄▄▄▄▄ ▐░█▄▄▄▄▄▄▄█░▌       ▐░▐░▌        ▄▄▄▄█░█▄▄▄▄ ▐░█▄▄▄▄▄▄▄█░▌         ▄▄▄▄█░░█▄▄▄  ▄▄▄▄▄▄▄▄▄█░▌"
printf "    ▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌        ▐░▌        ▐░░░░░░░░░░░▌▐░░░░░░░░░░▌         ▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌"
printf "     ▀▀▀▀▀▀▀▀▀▀▀  ▀▀▀▀▀▀▀▀▀▀▀          ▀          ▀▀▀▀▀▀▀▀▀▀▀  ▀▀▀▀▀▀▀▀▀▀           ▀▀▀▀▀▀▀▀▀▀▀  ▀▀▀▀▀▀▀▀▀▀▀ "
echo ""
echo -e $red " This tool is also for the latest covid-19 stats to diagnose your health "
echo -e $green " "
echo " Dev.Mohammed Info - From : Yemen - github.com/profionaldhim "
echo ""
echo -e $green ' ====================================================================================='

}
menue () {


echo -e $green   '{ -1- } ===> ' $white " Test YourSelfe"
echo ""
sleep 0
echo -e $green   '{ -2- } ===> ' $red " Covid stats - 19"
echo ""
sleep 0
echo -e $green   '{ -3- } ===> ' $white " Report an injury "
echo ""
sleep 0
echo -e $green   '{ -4- } ===> ' $red " Update "
echo ""
sleep 0
echo -e $green   "0- EXIT |-|"
echo "" 
echo "" 
sleep 0
echo ""
read -p "Enter The Number : " chc
if [ $chc = 1 ]
then

php test/Covid-19.php

fi
}


banner
menue
                                                                                                         
